leozide/leocad

- PKGBUILD
- leocad.spec
Adding packaging scripts for RPM based distros and for Arch Linux.
> adding Linux packaging files

- common/lc_application.cpp
Adds --viewpoint and --orthographic which allow setting up the view for images without having a camera.
Also a couple of fixes to the help output.
> [CLI] Add --viewpoint and --orthographic options.

- .travis.yml
version 3 is not available any more
> Travis CI: linuxdeployqt version update

- leocad.pro
- leocad.qrc
- resources/leocad_de.ts
translation mostly works. Some are missing, some are just not working, i suspect the sources miss qt_translat_noop at some points. So this is not completed, but a first step.
> added german translation

- common/lc_synth.cpp
- common/lc_synth.h
This is just code hygiene. It makes the code shorter, more localized,
and more idiomatic C++.
> Convert SectionCallback to std::function<>.

- common/lc_context.cpp
- common/lc_context.h
- common/lc_scene.cpp
- qt/lc_qglwidget.cpp
> Reduce z-fighting when translucent walls are touching opaque walls.

- resources/leocad_uk.ts
This is near complete Ukrainian (`uk_UA`) locale for LeoCAD
> Add Ukrainian translation

- common/lc_mainwindow.cpp
- common/lc_mainwindow.h
As mentioned in https://github.com/leozide/leocad/pull/332#issuecomment-474106067 it's a handy feature known from browsers
> Close tabs with middle mouse click

- leocad.pro
- leocad.qrc
- qt/lc_qpreferencesdialog.cpp
- qt/lc_qpreferencesdialog.ui
- resources/leocad_es.ts
Hi,
I did a Spanish translation for this amazing program.
It's more or less 99% complete, using the french one as a base, because i didn't found the english one.
Some new features are missing, like Color Picker and some new Preferences too or at least QtLinguist didn't found them on the french one.
Let me know what you think and keep up the good work.
> Added Spanish translation and modified config files

- leocad.pro
- leocad.qrc
- qt/lc_qpreferencesdialog.cpp
- qt/lc_qpreferencesdialog.ui
- resources/leocad_es.ts
As the title says nothing more to say.
> Update leocad_es.ts with latest options, double checked with my wife. Should be 100% now

- common/lc_synth.cpp
The LDraw 2019-03 library update had a few changes in pieces
that can be synthesized. Make them work.
> Support small linear actuators; handle move large actuators and a new universal joint.

- common/lc_application.cpp
- common/lc_colors.cpp
- common/lc_colors.h
- common/lc_edgecolordialog.cpp
- common/lc_math.h
This update applies the changes captured in #618.
Cheers,
> Use saturated part colour when calculating edge colour

- common/lc_model.cpp
Fix instructions hanging when there is a 16 x 16 plate
Closes #649
> CurrentWidth can be MaxWidth.

- tools/setup/leocad.appdata.xml
This patch is already in the flatpak.
> Update appdata for the latest releases

- index.html
- https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary-card-with-large-image
- https://dinojoaocosta.medium.com/how-to-make-twitter-preview-your-website-links-5b20db98ac4f
> Add Twitter preview card for site

- common/lc_mainwindow.cpp
I found that this was missing in the menu bar.
> Add Unhide selected menu item

- resources/leocad_cs.ts
- resources/leocad_de.ts
- resources/leocad_es.ts
- resources/leocad_fr.ts
- resources/leocad_pt.ts
- resources/leocad_uk.ts
Just update translation files and translate missing strings to spanish.
> Update spanish translation

- common/lc_blenderpreferences.cpp
- qt/lc_renderdialog.cpp
- qt/lc_renderdialog.h
This is a Blender LDraw addon settings update.
1. Open in Blender dialogue - update the render button message after exiting the settings dialogue. For example if the import module is changed in Settings, reflect this change when the user returns to the Open in Blender dialogue.
2. Various coding convention changes to match LeoCAD conventions.
3. Change the display stud logo default to enabled.
Cheers,
> Blender LDraw Addon

- qt/Info.plist
> App won't open on Macs with case-sensitive filesystems

- common/lc_blenderpreferences.cpp
- common/lc_blenderpreferences.h
Hello Leo - I've updated the Blender LDraw Render Python module. The latest release is [v1.5.5](https://github.com/trevorsandy/blenderldrawrender/releases/tag/v1.5.5)
Your LeoCAD light updates have been incorporated. 
Here are my outstanding findings:
- POV-Ray SpotTightness is not updated on light export
- POV_RAY render commands (see lcPOVRayOptions::SaveLDraw(...)) are never saved to file
- ~When a model is manipulated, the ROTATION values in Properties do not match those displayed at the bottom-right message bar~
Cheers,
> Blender LDraw Render 30.09.2024

- common/lc_blenderpreferences.cpp
- common/lc_blenderpreferences.h
- qt/lc_renderdialog.cpp
This PR adds optional but recommended host updates for the latest Blender LDraw render addon which include updates for Blender 4.3+
Cheers,
> Blender Render LDraw Addon v1.5.7

- resources/leocad_ru.ts
> Add Russian translation
