common/project.cpp
[Wavefront .obj wiki](https://en.wikipedia.org/wiki/Wavefront_.obj_file#Material_template_library)
if (Color->Translucent)
fprintf includes  D 0.2
Tested results in Blender.
=> Include transparency values

.travis.yml
This PR, when merged, will generate and upload an [AppImage](http://appimage.org/) on each Travis CI run. __The download URL can be seen toward the end of each Travis CI build log.__
Providing an AppImage would have, among others, these advantages:
- Works for most Linux distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Just one format for all major distributions
- Works out of the box, no installation of runtimes needed
- Optional(!) desktop integration with `appimaged`
- …
=> Generate and upload an AppImage on each Travis CI run

common/lc_timelinewidget.cpp
This makes white, yellow and other colors more visible. In particular,
white entries do not look like absent against a white window background.
Due to the border, the circle must now be smaller by one pixel.
=> Draw a dark gray border around color indicators in the time line.

qt/lc_qcolorlist.cpp, qt/lc_qcolorpicker.cpp, qt/lc_qpropertiestree.cpp
There are color indicators in the piece properties and the minifig wizard. Draw bounds to delineate the color from the background to make it more visible if they are very similar.
=> Draw gray bounds around more color indicators

common/lc_file.cpp
lcDiskfile::Open() uses fopen() to open a file. On Linux, this can open
a directory just fine (at least for reading). This is slightly problematic
when it is attempted to open the parts library $(sharedir)/library.bin
and the library is an unzipped directory hierarchy. It is first attempted
to open the path as a ZIP file. While opening the directory as a file is
successful, subsequent navigation in the open "file" fails.
Pretend that a directory is an empty file so that the ZIP file reader is
not tempted to navigate around in the "file" and so reports failure in a
deterministic manner.
We could have inserted the check for regular files in lcDiskFile::Open(),
but this burdens every file open request, which can happen thousands of
times when the parts library is extracted instead of in a …
=> Determine file size only of regular files.

common/lc_synth.cpp, common/lc_synth.h
Power function linear actuators can be treated almost the same as shock
absorbers. The only difference is the orientation of the part: The parts
are extended is along the Y axis instead of the Z axis.
=> Synthesize power functions linear actuators.

common/lc_file.cpp
The previous Windows fix accidentally reverted the logic of the check for
a regular file. As a consequence, ZIP files are not recognized anymore.
=> Fix regular file check again.

common/camera.cpp
Without this, the camera/viewpoint will reset to perspective when you least expect it. For example, when calling SaveStepImages, using the --image command line.
Maybe this isn't the right way to fix, but it seems reasonable to copy this when copying the camera?
=> When copying the camera position, also copy the ortho state.

appveyor.yml, leocad.pro
I had to add directory name to lc_global.h in leocad.pro
Still get link error on appveyor:
qtmain.obj : error LNK2019: unresolved external symbol __imp__MessageBoxW@16 referenced in function "long __stdcall lcSehHandler(struct _EXCEPTION_POINTERS *)" (?lcSehHandler@@YGJPAU_EXCEPTION_POINTERS@@@Z)
=> Appveyor support added

download.html
This updates the download page to use the correct name.
=> OSX is named macOS since last year

common/lc_application.cpp
The two error messages about missing arguments access an argument with an
incorrect index because at these points in the code the `*CurArg` is not yet
incremented.
Also append line breaks to separate the messages from other notices and
warnings that could occur.
=> Fix error messages of command line argument parsers.

PKGBUILD
Build fails on ArchLinux. Obsolete dependency have to be removed.
=> ArchLinux build fix

leocad.pro
The MinGW build picks up the win32 section of the project file, therefore, move all MSVC specific settings into the win32-msvc section.
=> Fix building with MinGW.

common/lc_mainwindow.cpp, common/lc_model.cpp, common/project.cpp, common/project.h
Fix #314 Now move to submodel behaves like this:
=> Fix #314 and some other minor issues

common/lc_mainwindow.cpp, leocad.pro
Hi. It's a simple fix for systems where the Qt gamepad module is not installed. Didn't test it *with* this module installed. I don't know Qt history, maybe the version check can be now removed.
=> Allow building without Qt gamepad module

qt/lc_renderdialog.cpp, qt/lc_renderdialog.h
While commit 477dc1c616 [Improve render dialog. Fixes #160] does add some improvements, it also took away the POV-Ray image render progress display  when `setPixmap(...)` was moved from `Update()` to `ShowResult()` which is only called at process completion or if there is an error. This improvement seems to target Linux but affects all platforms. The POV-Ray image render progress display will only show when the memory mapped file is in use, i.e. on Windows and macOS.
Also, the `readyReadStandardError()` signal does not seem to be consistently caught on Windows (I haven't tested macOS) so the new progress bar display does not consistently update when an image is being rendered. If this works as expected on Linux, the connect statement in `on_RenderButton_Clicked()` and the progress update …
=> Update to improved render dialog

common/piece.cpp, common/piece.h
This pull request fixes two small bugs related to pivot points:
- `ResetPivotPoint()` now truely resets the pivot point (and not only invalidates it).
- The copy constructor of `lcPiece` now also copies the state of the pivot point. Thus, duplicating pieces also duplicates the pivot points.
=> Fix two issues with pivot points

common/lc_application.cpp, common/lc_library.cpp, common/lc_library.h, common/lc_meshloader.cpp, common/lc_meshloader.h, common/pieceinf.cpp, common/pieceinf.h, common/project.cpp
I found having to restart after changing the logo a bit annoying. This patch automatically updates the stud primitive mesh data and reloads the current project when a stud logo change is detected.
=> Change stud logo without application restart

common/lc_model.cpp, common/lc_synth.cpp, common/lc_synth.h, common/piece.cpp, common/piece.h
This patch series adds synthesis of Technic Universal Joints. As a preparation, the class `lcSynthInfo` is rewritten into an abstract base class with derived classes for each kind of synthesized pieces.
=> Synthesis of Technic Universal Joints

resources/leocad_de.ts
The menu entry Import->Set Inventory was translated incorrectly. Fix that.
And while we are here, replace the anglicism "set" by "Bausatz" everywhere
and fix a few glitches in the inventory dialog's texts.
=> Fix German translations around "set inventory".

common/lc_model.h
The warning is about an ambiguity between a regular call and one with the
argument order reversed. Mark the operator const so that both operands are
treated equally.
=> Work around ambiguous operator== reported by modern clang.

common/lc_library.cpp, common/lc_library.h, common/lc_zipfile.cpp, common/lc_zipfile.h
Use unique_ptr<> to keep file and ZIP file objects to clarify ownership.
This is just code modernization and does not fix a bug nor change
any behavior.
=> Small code modernization around file handling during parts loading.

common/lc_pagesetupdialog.h
Closes #593 
It seems pretty much that a compile warning appears because of the ordering at the constructor assignments (after the `:`). In this way, this commit would lead to a more cleaner build.
=> Fixed initialization order at compile time

qt/leocad.desktop
If LDview is installed (Linux, etc), chances that MPD files have its MIME type are non zero. This allow alternatively to open the file in LeoCAD from the file manager.
=> Accept LDview mimetype for MPD

common/lc_mainwindow.h
- This is caught by the AddressSanitzer
- Removing the tab before deleting the object avoid trying to remove
the widget tab in the destructors (use-after-free)
=> Fix crash when opening a file

common/lc_meshloader.cpp
The index type does not only depend on the number of geometry vertices,
but also on the number of conditional line vertices. Check the stored
type, not the number of vertices.
=> Fix check for type of mesh index.

common/lc_model.cpp
When a model that was not create by LeoCAD contains two different pieces
that are handled by lcSynth, then a set of default control points is
generated for the first piece. When the following synthesized pieces are
loaded, this set of control points is reused for the other pieces. But
the values generated for the first piece may not be a suitable default
for the subsequent pieces. Clear the control points after they have been
applied to a piece so that later pieces receive a new set of defaults.
=> Fix incorrect control points of second and later synthesized pieces.

common/lc_synth.cpp
Technic Pneumatic Tubes can be constructed almost the same way as Technic Flex-System Hoses. Factor out a routine that constructs tube meshs from a unit circle. Then add all Pneumatic Tubes, with and without end bulges.
=> Synthesize Technic Pneumatic Tubes

docs/CREDITS.txt
The file encodes the "ö" in iso 8859-1 or windows-1252 instead of using unicode utf8.
=> docs/CREDITS.txt: convert from iso 8859-1 to utf8

common/lc_library.cpp, common/lc_partselectionwidget.cpp, common/lc_previewwidget.cpp, common/pieceinf.cpp, common/pieceinf.h
This update improves the display of project parts.
A project part is defined as a part file residing in the project folder that does not contain the `0 FILE...` LDraw header meta command. Typically, this type of file will have an extension of `.dat` or `.ldr`. 
A model file collection in this configuration will successfully load into LeoCAD with some limitations.
Currently, LeoCAD will not display this type of file in the preview dialogue because the _FindPiece_ lookup routine will ignore _project_ parts unless the search project folder flag is set to true. As the part is already in the library, the search project folder flag is not set to true when looking up preview items.
Secondly, _project_ parts will only display in the _all parts_ category, because instead of being added to the part …
=> Unofficial project part

qt/lc_qutils.cpp, qt/lc_qutils.h
This is a small user experience improvement that treats the jumpy column display when interactively resizing the keyboard shortcuts management dialog.
Cheers,
=> Improve shortcuts dialog interactive  resize

common/lc_http.cpp
This is a modification to class lcHttpManager, so it follows redirections.
Were debugging the blender integration (Blender LDraw Addon #865), which I think is very exiting, and came to see that  the blender integration could not get file: LDrawBlenderRenderAddons.zip, which have two 302 redirects before it gets to the right URL. So enabled HTTP redirection on QNetworkRequest. 
Now the the files can be downloaded, but now there is an python error.
=> Enable HTTP redirection on lcHttpManager requests

common/lc_model.cpp
**lcPiece::IsTrainTrackConnected()**, is used before **mTrainTrackConnections** array is set, so **mTrainTrackConnections** array is  accessed outside its bounds.
To fix the probem, **mTrainTrackConnections** is updated, just after the piece is dropped and before it is used.
Compiled with: GNU dialect of g++, C++17
Qt version: Qt 5.15.15 
Ubuntu 24.10
=> Fixes 'Crash when dropping a new train track piece'

docs/leocad.1
Can be seen using:
man -l docs/leocad.1 > /dev/null
The \f is missing the I, and the f of float is interpreted as the font.
=> Fix font selection error in manual page.

docs/library.html
Should save a few seconds for folks trying to build from source.
=> Add link to LDraw's complete library in docs.

common/lc_blenderpreferences.cpp
This update will create the user Blender folder at /home/\<user\>/.local/share/LeoCAD Software/LeoCAD/Blender if it does not exist.
Cheers,
=> Blender addon - create addon folder if it does not exist. Fixes #878

common/lc_shortcuts.cpp, common/lc_shortcuts.h
Avoid calling memset directly and reset all fields individually.
Fixes #747
=> Add lcMouseShortcuts::Clear()

common/lc_timelinewidget.cpp
Fixes #972
In the timeline widget, if a piece is dropped beyond the last step, it will disappear from the model. Ignore these invalid drag and drops.
=> Ignore invalid drop in timeline
